#!/bin/bash

title=`head -n1 $1`
title_pattern="BT403177"

message=`tail -n1 $1`
message_pattern="(02)"

if ! [[ "$title" = $title_pattern ]]; then
	echo "Use your special number in commit title"
	exit 1
fi

if ! [[ "$message" =~ $message_pattern ]]; then
	echo "Incorrect commit msg - Please include lab number"
	exit 1
fi
