pipeline{
    agent any

    parameters {
        string(name: 'Name')
        string(name: 'Version')
    }

    stages{
        stage('Build') {
            steps {
                echo 'BUILD'
                dir('INO/GCL01/AG401570/Lab05') {
                    sh 'docker build . -f dockerFile1 -t builder'
                }
            }
        }
        stage('Tests') {
            steps {
                echo 'TESTS'
                dir('INO/GCL01/AG401570/Lab05') {
                    sh 'docker build . -f dockerFile2 -t tester'
                }
            }
        }
        stage('Deploy') {
            steps {
                echo 'DEPLOY'
                sh 'docker run --volume /var/jenkins_home/workspace/Rurociag/INO/GCL01/AG401570/Lab05:/vo builder mv -n pcalc /v'
                dir('INO/GCL01/AG401570/Lab05') {
                    sh 'docker build . -f dockerFile3 -t deploy'
                }
                sh 'docker run --volume /var/jenkins_home/workspace/Rurociag/INO/GCL01/AG401570/Lab05:/pcalc -d -p 3000:80 deploy'
                sh 'docker stop $(docker ps -a -q)'
            }
        }
    }

}
