pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                script {
                    sh 'docker volume prune -f'
                    git 'https://github.com/InzynieriaOprogramowaniaAGH/MDO2022_S.git'
                    sh 'git checkout WJ400220'
                    sh 'git pull origin'
                    sh 'cd ITE/GCL03/WJ400220/Lab05/dockerfiles/ ; docker build --no-cache -t build_node:latest . -f ./build.dockerfile'
                    sh 'docker volume create volume_out'
                    sh 'docker run --mount type=volume,src="volume_out",dst=/node_app/files build_node:latest bash -c "ls -l && cd .. && ls -l && cp -r /testing-node-apps /files"'
                }
           }
        }
        stage('Test') {
            steps {
                sh 'cd ITE/GCL03/WJ400220/Lab05/dockerfiles/ ; docker build --no-cache -t test_node:latest . -f ./test.dockerfile'
            }
        }
        stage('Deploy') {
            steps {
                sh 'docker rm -f deploy_node || true'
		sh 'docker run -dit --name deploy_node --mount type=volume,src="volume_out",dst=/dest node'
		sh 'docker container exec deploy_node sh -c "ls -l && cd dev && ls -l && cd ../etc && ls -l && cd ../dest && ls -l && cd files && ls -l"'
		sh 'docker container exec deploy_node sh -c "cd dist && ls -l && npm run validate"'
            }
        }
    }
}

