pipeline {
    agent any
    stages {
        stage('build') {
            steps {
		echo 'Building'
		
                sh 'docker build -t builder . -f ITE/GCL03/JJ400051/Project/DockerfileBuild'
		sh 'docker run --name dock -dit --rm builder'
		sh 'docker cp dock:irssi/build/src/fe-text/irssi .'
		sh 'docker kill dock'
	    }
        }
        stage('test') {
            steps {
                echo 'Testing'
		sh 'docker build -t tester . -f ITE/GCL03/JJ400051/Project/DockerfileTest'
		sh 'docker run tester'

            }
        }
	stage('deploy') {
	    steps {
		echo 'deploying'
		    sh 'docker container kill deployer'		    
		    sh 'docker container rm deployer'
		    sh 'docker run --name deployer -dit debian'
		    sh 'docker cp irssi deployer:.'
		    sh 'docker container exec deployer sh -c "apt-get update -y"'
		    sh 'docker container exec deployer sh -c "apt-get install -y libssl-dev glib-2.0 libghc-terminfo-dev libutf8proc-dev"'
		    sh "docker container exec deployer sh -c './irssi -v'"

	    }
	}
	stage('publish') {
	    steps {
                sh 'docker container rm publisher'
		echo 'publishing'
		sh 'mkdir publisher'
		sh 'cp irssi publisher'
		sh "tar -jcf version${params.version}.tar.xz Dir"
		archiveArtifacts artifacts: "version${params.version}.tar.xz"		
		sh 'docker container kill publisher'
	    }
	}
    }
}
