pipeline {
    agent any
    stages {
        stage('build') {
            steps {
		echo 'Building'
                sh 'docker build -t builder . -f ITE/GCL03/JJ400051/Project/DockerfileBuild'
		sh 'docker run --name dock -d --rm builder'
		sh 'docker cp dock:irssi/build/src/fe-text/irssi .'
	    }
        }
        stage('test') {
            steps {
                echo 'Testing'
		sh 'docker build -t tester . -f ITE/GCL03/JJ400051/Project/DockerfileTest'
		sh 'docker run tester'

            }
        }
	stage('deploy') {
	    steps {
		echo 'deploying'
		    sh 'docker container rm deployer'
		    sh 'docker container create --name deployer debian'
		    sh 'docker cp build deployer:.'
		    sh 'docker container exec deployer sh -c "apt-get update -y"'
		    sh 'docker continer exec deployer sh -c "apt-get install -y build-essential"'
		    sh 'docker continer exec deployer sh -c "./irssi"'
		    
	    }
	}
	stage('publish') {
	    steps {
		echo 'publishing'
		sh 'mkdir publisher'
		sh 'cp irssi publisher'
		sh "tar -jcf version${params.version}.tar.xz Dir"
		archiveArtifacts artifacts: "version${params.version}.tar.xz"
	    }
	}
    }
}
