pipeline {
    agent any

    stages {
        stage('Repository') {
            
            agent {
                    docker{
                        image 'ubuntu:latest'
                    }
                }
            
            steps {
                
                sh 'docker volume create vol-in'
                sh 'docker volume create vol-out'
                sh 'docker run -it --name cloneRepository --mount source=vol-in,destination=/inputV ubuntu:latest'
                sh 'apt-get -y update'
                sh 'apt-get -y install git'
                sh 'cd inputV'
                sh 'git clone https://github.com/InzynieriaOprogramowaniaAGH/MDO2022_S.git'
                sh 'exit'
                    
            }
        }
        stage('Build') {
            steps {
                echo 'Building..'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}
