pipeline {
    agent any

    stages {
	stage('Build') {
            steps {
		sh 'docker volume create build'
		git 'https://github.com/InzynieriaOprogramowaniaAGH/MDO2022_S.git'
		sh 'git checkout DK403865'
		sh 'git pull origin'
		sh 'cd ITE/GCL03/DK403865/Lab06/Build ; docker build -t build_base:latest .'
		sh 'docker run --rm -d --name dotnet_build --mount source=build,target=/build build_base:latest'            
	}
        }
	stage('Test') {
            steps {
                sh 'cd ITE/GCL03/DK403865/Lab05/Dockerfiles/DockerfileTest ; docker build -t test_base:latest .'  
            }
        }

        stage('build-dotnet-deps-image') {
            steps {
		sh 'git pull origin'
		sh 'cd ITE/GCL03/DK403865/Lab06/DotnetDeps ; docker build -t dotnet_deps:latest .'            
	}
        }
	stage('deploy') {
            steps {
		sh 'docker stop dotnet_deploy'
                sh 'docker run --rm -i -t -d --name dotnet_deploy --mount source=build,target=/build dotnet_deps:latest'
		//sh 'docker exec -d dotnet_deploy bash ls'
		sh 'docker exec -d dotnet_deploy bash "cd build ; dotnet run"'

		sh 'docker logs -f --tail 50 dotnet_deploy'
		//sh 'cd ITE/GCL03/DK403865/Lab06/Deploy ; docker build --no-cache --progress string -t dotnet_deploy:latest .'
            }
        }

    }
}
