#!/usr/bin/python3
# -*- coding: UTF-8 -*-

import sys
import re

messageFile = sys.argv[1]
file = open(messageFile, 'r')
message = file.readlines()
file.close()
title= re.compile("[A-Z]{2}[0-9]{6}\n")
if not title.match(message[0]):
    print("Wrong title")
    sys.exit(-1)

print("All good ")