#!/usr/bin/python3
# -*- coding: UTF-8 -*-

import sys
messageFile = sys.argv[1]
file = open(messageFile, 'r')
message = file.readlines()
file.close()
name="WM400039"
if not name.match(message[0]):
    print("Wrong title")
    sys.exit(-1)
print("All good ")
