#!/usr/bin/env python

import sys, os
import subprocess as sp

message = sp.getoutput('git log -1 --pretty=%B')
splitter = "release-version "
if splitter in message:
  newTag = message.split(splitter)[1].split(" ")[0]
  print("=============== RELEASE!!!! ==============")
  if newTag is not None:  
    print(f"Last tag: {sp.getoutput('git describe --abbrev=0 --tags')}\nNew tag: {newTag}")
    result = sp.getoutput(f"git tag {newTag} HEAD && git push && git push origin {newTag}")
    print(result)
    print(sp.getoutput(f'curl.exe -X POST --data TAG={newTag} --user "admin:1128d23201b0b17689e6048711cab834d8" "http://localhost:8080/job/LAB07/buildWithParameters"'))
    print("============================================")
