pipeline {
    agent any

     parameters {
        string(name: 'Version', defaultValue: '1.0.0', description: 'Version')
        booleanParam(name: 'Promote', defaultValue: true, description: 'Promote statement')
        string(name: 'Build_files', defaultValue: './ITE/GCL08/MW401139', description: 'build files path')
    }

    stages {
        stage('Build') {
            steps {
                echo 'building node-red'
				dir("${params.Build_files}") {
                    sh 'docker build . -f docker_build -t node-red_build'
				}
                
            }
        }
        
        stage('Tests') {
            steps {
                echo 'testing node-red'
				dir("${params.Build_files}") {
                    sh 'docker build . -f docker_test -t node-red_test'
				}
            }
        }
        
         
        // stage('Deploy') {
        //     steps {
        //         echo 'deploying node-red'
        //         sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
        //         sh '''
        //         docker images
        //         docker tag node-red_build: mihalatestf70/node-red-devops-deploy
        //         docker push mihaf70/node-red-devops-deploy
        //         '''
        //     }
        // }

        // stage('Prepare'){
        //     when {
        //         expression {return params.Promote}
		//     }
        //     steps {
        //         echo 'Preparing publish'
        //         sh 'ls /var/jenkins_home/workspace/artifacts || mkdir /var/jenkins_home/workspace/artifacts'
        //     }
        // }

         stage('Publish'){
            when {
                expression {return params.Promote}
		    }
            steps {
                echo 'Publish'
                dir("${params.Build_files}") {
                    sh 'docker build . -f docker_publish -t node-red_publish'
				}
                sh "docker run --volume /var/jenkins_home/workspace/node-red-pipeline:/finalArchive node-red_publish mv archive.tar.xz /finalArchive"
                 dir('/var/jenkins_home/workspace/node-red-pipeline/finalArchive'){
                    sh 'ls'
			        archiveArtifacts artifacts: "archive.tar.xz"
			    }
            }
        }

    //    stage('Publish') {
	// 	    when {
    //             expression {return params.Promote}
	// 	    }
	// 	    agent {
    //             docker {
    //                 image 'node-red_build:latest'
    //                 args '--rm --mount "type=volume,src=output-volume,dst=/usr/local/myapp" --mount "type=bind,source=/var/jenkins_home/workspace/artifacts,dst=/usr/local/copy" -u root:root'
    //             }
    //         }
	// 		steps {
	// 		    sh 'rm -rf /usr/local/copy/* || true'
	// 		    sh "cd /usr/local/myapp/express && npm version ${params.Version} && npm pack"
	// 		    sh "mv /usr/local/myapp/express/express-${params.Version}.tgz /usr/local/copy"
	// 		    dir('/var/jenkins_home/workspace/artifacts'){
	// 		        archiveArtifacts artifacts: "express-${params.Version}.tgz"
	// 		    }
	// 		}
	// 	}
	 }

	post {
        success {
            echo 'Pipeline succsess'
        }
        failure {
            echo 'Pipeline fail'
        }
    }
}