pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'building node-red'
				dir("./ITE/GCL08/MW401139") {
                    sh 'docker build . -f docker_build -t node-red_build'
				}
                
            }
        }
        
        stage('Tests') {
            steps {
                echo 'testing node-red'
				dir("./ITE/GCL08/MW401139") {
                    sh 'docker build . -f docker_test -t node-red_test'
				}
            }
        }
        
         stage('Deploy') {
            steps {
                echo 'runnning node-red'
				dir("./ITE/GCL08/MW401139") {
                    sh 'docker build . -f docker_deploy -t node-red_deploy'
				}
            }
        }
    }
}