
  
pipeline 
{
    agent any
    stages
     {
        stage('Build') 
        {
            steps 
            {
               sh 'docker build -t build:latest . -f ./ITE/GCL04/DG304299/Lab05/docker_build'
               
            }
        }

         stage('contoll') 
        {
            steps 
            {
               sh 'docker ps'
            }
        }

         stage('Test') 
        {
            steps 
            {
               
               sh 'docker build -t build:latest . -f ./ITE/GCL04/DG304299/Lab05/docker_test'
            }
        }
    }
}