
  
pipeline 
{
    agent any
    stages
     {

          stage('Clone') 
        {
            steps 
            {
              sh 'docker container prune -f'
              sh 'docker volume prune -f'
              sh 'docker volume  create --name repo_vol'
              sh 'docker volume  create --name build_vol'
              sh "docker build -t clone . -f ./ITE/GCL04/DG304299/Lab05/docker_clone"
              sh "docker run -v repo_vol:/Guess-Word-Game clone"           
            }
        }


        stage('Build') 
        {
            steps 
            {
               sh 'docker build -t build . -f ./ITE/GCL04/DG304299/Lab05/docker_build'
               sh 'docker run --name build_container -v repo_vol:/Guess-Word-Game -v build_vol:/build -v ${PWD}:/public build'
            }
        }

         stage('Test') 
        {
            steps 
            {
               sh 'docker build -t test . -f ./ITE/GCL04/DG304299/Lab05/docker_test'
               sh 'docker run --name test_container -v repo_vol:/Guess-Word-Game test'
            }
        }

          stage('Deploy') 
        {
            steps 
            {
               sh 'docker build -t deploy . -f ./ITE/GCL04/DG304299/Lab05/docker_deploy'
               
                    script
                    {
                            try 
                            {
                                sh 'docker run --name deploy_container -v build_vol:/build deploy'
                            } 
                            catch (Exception e) 
                            {
                                echo 'Exception occurred: ' + e.toString()
                            }
                    }
            }
        }

    }
}