
  
pipeline 
{
    agent any
    stages
     {

          stage('Clone') 
        {
            steps 
            {
               sh 'docker container prune -f'
               sh 'docker volume prune -f' 
               sh "docker volume create clone"
               sh "docker run --mount source=clone,target=/app --name clone ubuntu"
               sh "rm -rf Guess-Word-Game"
               sh "git clone https://github.com/LondonJim/Guess-Word-Game.git"
               sh "docker cp ./Guess-Word-Game clone:/app"
               sh "docker rm -f clone"            
            }
        }


        stage('Build') 
        {
            steps 
            {
               sh "docker rm -f builder"
               sh "docker volume create build"
               sh 'docker build -t app_build:latest . -f ./ITE/GCL04/DG304299/Lab05/docker_build'
               sh "docker run --rm --mount source=clone,target=/app --mount source=build,target=/app/Guess-Word-Game/build --name build app_build:latest"
            }
        }

    }
}