#!/bin/sh
#
# An example hook script to check the commit log message.
# Called by "git commit" with one argument, the name of the file
# that has the commit message.  The hook should exit with non-zero
# status after issuing an appropriate message if it wants to stop the
# commit.  The hook is allowed to edit the commit message file.
#
# To enable this hook, rename this file to "commit-msg".

REDBOLD='\033[0;31;1m'
GREENBOLD='\033[0;32;1m'
NORMAL='\033[0m'

echo -e "\nTesting commit message..."

if test $(cat $1) = PW404121
then
  echo -e "${GREENBOLD}Commit message is equal PW404121 ${NORMAL}\n"
else
  echo -e "${REDBOLD}Commit message is NOT equal PW404121 ${NORMAL}\n"
  exit 1
fi
