#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

REDBOLD='\033[0;31;1m'
GREENBOLD='\033[0;32;1m'
NORMAL='\033[0m'

echo -e "\nTesting commit content..."

if git diff --cached | grep "/Lab02/"
then
  echo -e  "${GREENBOLD}Commit contain current laboratory number - 02 ${NORMAL}\n"
else
  echo -e "${REDBOLD}Commit does NOT contain current laboratory number - 02 ${NORMAL}\n"
  exit 1
fi