pipeline {
    agent any
    parameters {
        booleanParam(name: "promote",
            defaultValue: false,
            description: "Promote to new version, when successful?")
        string(name: "version",
            defaultValue: "",
            description: "Type in verion number:")
    }
    stages {
        stage("Git") {
            steps {
                sh "docker system prune --all -f"
                sh "docker build -t git:latest . -f ./ITE/GCL03/DG401340/Lab05/git_dockerfile/Dockerfile"
                sh "docker run --name clone --rm --mount source=in,target=/volume_in git:latest"
            }
        }
        stage("Build") {
            steps {
                sh "docker build -t build:latest . -f ./ITE/GCL03/DG401340/Lab05/build_dockerfile/Dockerfile"
                sh "docker run --name build --rm --mount source=in,target=/volume_in --mount source=out,target=/volume_out build:latest"
            }
        }
        stage("Test") {
            steps {
                echo "tests"
            }
        }
        stage("Deploy") {
            steps {
                sh "docker run -d --name copy --mount source=out,target=/volume_out busybox true"
                sh "docker exec copy bash -c \"rm -rf /volume_out/target/extract && mkdir -p /volume_out/target/extract && cp -f /volume_out/target/DiscordSRV* /volume_out/target/extract && rm /volume_out/target/extract/*sources*\""
                sh "rm -rf ./artifacts && mkdir artifacts"
                sh "docker cp copy:/volume_out ./artifacts "
                sh "mv ./artifacts/volume_out/target/extract/*.jar ./artifacts"
                sh "rm -rf ./artifacts/volume_out"
                sh "docker rm copy"
                waitUntil {
                    sh "docker run -d --name mc --mount type=bind,source=/artifacts,target=/plugins itzg/minecraft-server discord help"
                }
                sh "docker rm mc"
                echo "Deploy"
            }
        }
        stage("Publish") {
            steps {
                script {
                    if(params.promote) {
                        sh "mv ./artifacts/DiscordSRV* ./artifacts/DiscordSRV_${params.version}"
                        sh "ls -a ./artifacts"
                        archiveArtifacts artifacts: "artifacts/*.jar"
                    }
                    else {
                        echo "Everything was successful, but not promoting to new version!"
                    }
                }
            }
        }
    }
}
