FROM node:lts
WORKDIR /app

CMD apt-get update; apt-get upgrade -y; apt-get install -y rpm
CMD git config http.sslVerify false
CMD cd /app
CMD export LINUX_TARGET=deb
CMD git clone https://github.com/wireapp/wire-desktop.git
CMD cd ./wire-desktop
CMD yarn
CMD yarn build:linux