pipeline {
	agent any

	stages {

        stage('Build') {
			steps {
                
               dir ('Grupy/Grupa01/IB402983/Docker/Berty'){
				    sh 'docker-compose up build_agent'
                }
            }
            post {
                failure {
                    echo 'ERROR IN BUILDING'
                }
                success {
                    echo 'SUCCESS IN BUILDING'
                }
            }
        }

		stage('Test') {
			steps {

                sh 'ls'

                dir ('Grupy/Grupa01/IB402983/Docker/Berty'){
				    sh 'docker-compose up test_agent'
                }
            }
            post {
                failure {
                    echo 'ERROR IN TESTING'
                }
                success {
                    echo 'SUCCESS IN TESTING'
                }
            }
        }

        stage('Deploy') {

			steps {

                
			echo 'TEST123'
                
            }
            post {
                failure {
                    echo 'ERROR IN DEPLOYING'

           
                }
                success {
                    echo 'SUCCESS IN DEPLOYING'
                }
            }
        }

    
    }
}