pipeline {
	agent any
	environment {
	NPM_USR = credentials('jenkins-npm-usr')
	NPM_PSW = credentials('jenkins-npm-psw')
} 
	stages {
		stage('Build') {
			steps {
				sh 'docker run -f build_dockerfile'
			}
		}
	}
}


