pipeline {
    agent any 
    stages {
        stage('Build') { 
            steps {
                echo 'aa'
            }
        }
        stage('Test') { 
            steps {
                echo 'bb'
            }
        }
        stage('Deploy') { 
            steps {
                echo 'cc'
            }
        }
    }
}
