pipeline {
	agent any
    parameters {
        string(name: 'BRANCH', defaultValue: 'master', description: '')
        string(name: 'VERSION', defaultValue: '1.0.0', description: '')
        booleanParam(name: 'PROMOTE', defaultValue: false, description: '')
        }
  	stages {
        stage("Clone"){
            steps {
              sh 'docker container prune -f'
              sh 'docker volume prune -f'
              sh 'docker volume  create --name repo_vol'
              sh "docker build -t dethClone . -f ITE/GCL06/AP401497/Lab05/Clone/Dockerfile"
              sh "docker run -e BRANCH=${BRANCH} -v repo_vol:/deth dethClone"
                }
              }
        stage("Build") {
            steps {
                sh 'docker build -t dethBuild . -f ITE/GCL06/AP401497/Lab05/Build/Dockerfile'
                sh 'docker run -v repo_vol:/deth -v ${PWD}:/public dethBuild'            
            }
        }
        stage("Test") {
            steps {
                sh 'docker build -t dethTest . -f ITE/GCL06/AP401497/Lab05/Test/Dockerfile --build-arg image=deth_builded'
                sh 'docker run  -v repo_vol:/deth dethTest'
        }
  	}      

    post {
         always{
            cleanWs()
         }
    }
}
