pipeline {
    agent any
    
    stages {
        stage('build') {
            steps {
                sh 'docker build -t buildirssi . -f ITE/GCL04/SK403390/Lab05/DockerfileBuild'
		sh 'docker run --name tempContainer -dit --rm buildirssi'
		sh 'rm -r fe-text'
		sh 'docker cp tempContainer:irssi/build/src/fe-text .'
		sh 'docker kill tempContainer'
		sh 'ls'
		sh 'ls fe-text'
            }
        }
        stage('test') {
            steps {
                sh 'docker build -t testirssi . -f ITE/GCL04/SK403390/Lab05/DockerfileTest'
		sh 'docker run testirssi'
            }
        }
	stage('deploy') {
	    steps {
		sh 'docker kill deployContainer2 || true'
		sh 'docker run --rm --name deployContainer2 -dit ubuntu'
		sh 'docker cp fe-text deployContainer2:.'
		sh 'docker container exec deployContainer2 sh -c "apt-get update"'
		sh 'docker container exec deployContainer2 sh -c "DEBIAN_FRONTEND="noninteractive" apt-get install -y libglib2.0"'
		sh "docker container exec deployContainer2 sh -c 'apt-get install -y libutf8proc-dev'"
		sh 'docker container exec deployContainer2 ls fe-text'
		sh "docker container exec deployContainer2 sh -c './fe-text/irssi --version'"
		sh 'docker kill deployContainer2'
	    }
	}
    }
}
