pipeline {
    agent any
    
    stages {
        stage('build') {
            steps {
                sh 'docker build -t buildirssi . -f ITE/GCL04/SK403390/Lab05/DockerfileBuild'
		sh 'docker run --name ContainerTemp -dit --rm buildirssi'
		sh 'mkdir tempData'
		sh 'docker cp ContainerTemp:irssi/Build/src data'
		sh 'ls'
		sh 'ls tempData' 
            }
        }
        stage('test') {
            steps {
                sh 'docker build -t testirssi . -f ITE/GCL04/SK403390/Lab05/DockerfileTest'
		sh 'docker run testirssi'
            }
        }
    }
}
