pipeline {
    agent any
    
    stages {
        stage('build') {
            steps {
                sh 'docker build -t buildirssi . -f ITE/GCL04/SK403390/Lab05/DockerfileBuild'
		sh 'docker run --name ContainerTemp2 -dit --rm buildirssi'
		sh 'mkdir tempData2'
		sh 'docker cp ContainerTemp2:irssi/Build/irssi/src data'
		sh 'docker kill ContainerTemp2'
		sh 'ls'
		sh 'ls tempData' 
            }
        }
        stage('test') {
            steps {
                sh 'docker build -t testirssi . -f ITE/GCL04/SK403390/Lab05/DockerfileTest'
		sh 'docker run testirssi'
            }
        }
    }
}
