pipeline {
    agent any

    stages {
        stage('build') {
            steps {
                dir('INO/GCL02/PP401460/Lab05') {
                    sh '''
                        echo 'Creating \'out volume\' and \'in volume\'...'
                        docker volume create vol_in
                        docker volume create vol_out 
                        echo 'Building ...'
                        docker build -t builder -f ./Build.dockerfile .
                        docker run --mount source=vol_out,destination=/build builder cp /mle/mle /build
                    '''
                }
            }
        }
        stage('test') {
            steps {
                dir('INO/GCL02/PP401460/Lab05') {
                    sh '''
                        echo 'Testing ...'
                        docker build -t tester -f ./Test.dockerfile .
                    '''
                }
            }
        }
        stage('deploy') {
            steps {
                dir('INO/GCL02/PP401460/Lab05') {
                    sh '''
                        echo 'Deploying ...'
                        docker build -t deployer -f ./Deploy.dockerfile .
                        docker run -v vol_out:/build deployer 
                    '''
                }
            }
        }
        stage('publish') {
            steps {
                dir('INO/GCL02/PP401460/Lab05') {
                    sh '''
                        echo 'Publishing ...'
                        docker build -t publisher -f ./Publish.dockerfile .
                        docker run --mount source=vol_out,destination=/publish publisher mv /mle.deb /publish
                    '''
                }
            }
        }
    }
}
