pipeline {

  agent any
  
  	stages {
            stage("Clone"){
                steps {
             		  sh "docker system prune --all -f"
              		 sh 'docker volume  create --name repo_vol'
             		 sh 'docker volume  create --name build_vol'
             		 sh "docker build -t clone . -f ./ITE/GCL06/JP300987/Lab05/dockerfile_clone"
             		 sh "docker run -v repo_vol:/Deltachat clone" 
                    }
                }
            stage('Build') 
        	{
            steps 
            		{
           	
               sh 'docker build -t build . -f ./ITE/GCL06/JP300987/Lab05/dockerfile_build'
               sh 'docker run --name build_container -v repo_vol:/Deltachat -v build_vol:/build build'
            		}
        	}
        }
}
