pipeline {
    agent any
    stages {
        stage('Building') {
            steps {
                dir('.') {
                    sh 'cd ITE/GCL03/ŁG403881/Lab05/scm'
                    sh 'docker build -t build:latest . -f DockerBuild'
                }
            }
        }
    }
}
