pipeline {
    agent any
    stages {
        stage('Building') {
            steps {
                    git 'https://github.com/InzynieriaOprogramowaniaAGH/MDO2022_S.git'
		    sh 'git checkout ŁG403881'
		    sh 'git pull origin'
                    sh 'cd ./ITE/GCL03/ŁG403881/Lab05/scm/; docker build -t build:latest build/'
            }
        }
    }
}
