FROM node:16-alpine as git-install
RUN apk add --no-cache dumb-init git bash

FROM git-install as repo
RUN git clone https://github.com/wireapp/wire-webapp app
WORKDIR /app
RUN yarn
RUN mv .env.localhost .env
RUN yarn build:prod

