pipeline {
    agent any
    stages {
        stage("Prebuild") {
            agent {
                dockerfile {
                    dir "/var/jenkins_home"
                    args "-v /input-volume:/input-volume -v /output-volume:/output-volume"
                    additionalBuildArgs "--target prebuild"
                }
            }
            steps {
                echo "Stage: Prebuild"
            }
        }
        stage("Build") {
            steps {
                echo "Stage: Build"
                sh """
                docker build 
                --target build
                -t ava-build:1.0
                .
                """
            }
        }

        stage("Test") {
            steps {
                echo "Stage: Test"
                sh "docker build --target test -t ava-test:1.0"
            }
        }

        stage("Deploy") {
            steps {
                echo "Stage: Deploy"
            }
        }

        stage("Publish") {
            steps {
                echo "Stage: Publish"
            }
        }
    }
}
