pipeline {
    agent any

    stages {
        stage('Test') {
            steps {
                git 'https://github.com/aleksanderfilek/wire-desktop-devops.git'
                dir('Docker') {
                    sh 'docker-compose up'
                }
            }
            post {
                success {
                    echo '------------Successful test------------'
                    emailext attachLog: true,
                    body: "${currentBuild.currentResult}: Job ${env.JOB_NAME} build ${env.BUILD_NUMBER}",
                    recipientProviders: [developers(), requestor()],
                    subject: "Success Jenkins Tests",
                    to: 'filekaleksander@gmail.com'
                }
            
                failure {
                    echo '------------Failed test------------'
                    emailext attachLog: true,
                    body: "${currentBuild.currentResult}: Job ${env.JOB_NAME} build ${env.BUILD_NUMBER}",
                    recipientProviders: [developers(), requestor()],
                    subject: "Failed Jenkins Tests",
                    to: 'filekaleksander@gmail.com'
                }
            }
        }
    }
}