#!/bin/sh
#
# An example hook script to check the commit log message.
# Called by "git commit" with one argument, the name of the file
# that has the commit message.  The hook should exit with non-zero
# status after issuing an appropriate message if it wants to stop the
# commit.  The hook is allowed to edit the commit message file.
#
# To enable this hook, rename this file to "commit-msg".


echo -e "\nChecking out commit message..."

if test $(cat $1) = WM400178
then
  echo -e "Hook operation went successfully! Commit message is equal to WM400178\n"
else
  echo -e "error! Commit message should containt both your index number and initials.  \n"
  echo -e "The pattern is: <initials><index number>, for example: WM400178  \n"
  exit 1
fi