#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".


echo -e "\nChecking out commit message..."

if git diff --cached | grep "/Lab02/"
then
  echo -e  "hook operation went successfully! Commit message contain current laboratory number \n"
else
  echo -e "Commit must contain current laboratory number. \n"
  exit 1
fi