pipeline {
	agent any
	stages {

        stage('Build') {
			steps {
                
               dir ('Grupy/Grupa01/JC401889/Lab07/Docker'){
				    sh 'docker-compose up build_agent'
                }
            }
            post {
                failure {
                    echo 'ERROR IN BUILDING'
                }
                success {
                    echo 'SUCCESS IN BUILDING'
                }
            }
        }

		stage('Test') {
			steps {

                sh 'ls'

                dir ('Grupy/Grupa01/JC401889/Lab07/Docker'){
				    sh 'docker-compose up test_agent'
                }
            }
            post {
                failure {
                    echo 'ERROR IN TESTING'
                }
                success {
                    echo 'SUCCESS IN TESTING'
                }
            }
        }
    }
}