FROM node:14-alpine3.15
WORKDIR ./
RUN apk add git
RUN apk add python2
RUN git clone https://github.com/gothinkster/vue-realworld-example-app.git
WORKDIR /vue-realworld-example-app
RUN npm install
RUN npm build
