pipeline {
    agent any
    stages{
        
        stage('Build') {
            steps {
    
                echo 'BUILD'
                git branch: 'JKL302701', url: 'https://github.com/InzynieriaOprogramowaniaAGH/MDO2022_S.git'
                dir('INO/GCL01/JKL302701/lab05') {
                    sh 'docker build . -f df1.dockerfile -t builder'
                }
            }
        }
        
        stage('Tests') {
            steps {
                echo 'TESTS'
                dir('INO/GCL01/JKL302701/lab05') {
                    sh 'docker build . -f df2.dockerfile -t tester'
                }
            }
        }
        
        
        
        
        
    }
    

}
