pipeline 
{
			
	agent any

	stages 
	{
	stage('Clone') 
        	{
            steps 
            		{
               		sh 'docker container prune -f'
               		sh 'docker volume prune -f' 
               		sh 'docker build -t app_build:latest . -f ./ITE/GCL06/AP304152/Lab05/docker_clone'
               		sh "docker run --name clone --rm --mount source=in,target=/volume_in git:latest"
        		}
		}

        stage('Build') 
        	{
            steps 
            		{
           	echo 'build'
               
            		}
        	}
		
	}
}
