pipeline 
{
			
	agent any

	stages 
	{
	stage('Clone') 
        	{
            steps 
            		{
               		
				
			sh "docker system prune --all -f"
             		 sh 'docker volume  create --name repo_vol'
             		 sh 'docker volume  create --name build_vol'
             		 sh "docker build -t clone . -f ./ITE/GCL06/AP304152/Lab05/docker_clone"
             		 sh "docker run -v repo_vol:/Cytoscape clone"           
        		}
		}

        stage('Build') 
        	{
            steps 
            		{
           	
                //sh 'docker build -t build . -f ./ITE/GCL06/AP304152/Lab05/docker_build'
               //sh 'docker run --name build_container -v repo_vol:/Cytoscape -v build_vol:/build build'
            		}
        	}
		
	stage('Test') 
       		{
            steps 
            		{
               sh 'docker build -t test . -f ./ITE/GCL06/AP304152/Lab05/docker_test'
               sh 'docker run --name test_container -v repo_vol:/Cytoscape test'
            		}
        	}
		
	}
}
