pipeline {
    agent {
        node {
            label 'TestNode'
        }
    }
    parameters {
        string(name: 'BRANCH', defaultValue: 'main', description: 'Choose your brach name - default is set to master')
        string(name: 'NPM_TOKEN', defaultValue: '', description: 'Token')
        string(name: 'PROMOTE', defaultValue: 'no', description: 'To promote or not to promote')
    }
    stages {
        stage('git') {
            steps {
                git credentialsId: '1',
                url: 'https://github.com/InzynieriaOprogramowaniaAGH/MDO2022_S',
                branch: "${params.BRANCH}"
            }
        }
        stage('Build') {
            steps {
                sh 'docker volume create vol-in'
                sh 'docker volume create vol-out'
                sh 'docker build -t base -f ITE/GCL04/PK400223/Lab05/Dockerfiles/Dockerfile-prebuilder  ITE/GCL04/PK400223/Lab05/Dockerfiles/'
                sh "docker build -t devopsprojekt --build-arg NPM_TOKEN=${params.NPM_TOKEN} -f ITE/GCL04/PK400223/Lab05/Dockerfiles/Dockerfile-builder  ITE/GCL04/PK400223/Lab05/Dockerfiles/"
                sh "docker build -t tester -f ITE/GCL04/PK400223/Lab05/Dockerfiles/Dockerfile-tester  ITE/GCL04/PK400223/Lab05/Dockerfiles/" 
                sh "docker build -t runner -f ITE/GCL04/PK400223/Lab05/Dockerfiles/Dockerfile-runner  ITE/GCL04/PK400223/Lab05/Dockerfiles/" 
            }
        }
       stage('Test') {
           steps {
               sh 'docker run -d -v vol-out:/root/.npm/_logs tester'
           }
        }
       stage('Deploy') {
             steps {
               sh 'docker run --name app -d -v vol-out:/vue-realworld-example-app/node_modules -p 8080:8080 runner'
             }
         }
       stage('Publish') {
            when {
                expression {params.PROMOTE.contains("yes")}
            }
           steps {
                withCredentials([gitUsernamePassword(credentialsId: "1", ToolName: 'git-tool')]){
                    sh 'docker exec app sh -c "git config --global user.email "polokol13@gmail.com""'
                    sh 'docker exec app sh -c "git config --global user.name "Przemyslaw Kudriawcew""'
                    sh 'docker exec app sh -c "npm version 0.${BUILD_NUMBER}.0"'
                    sh 'docker exec app sh -c "npm publish"' 
                }
           }
       }
    }
    post { 
        always { 
                sh 'docker stop app'
                sh 'docker system prune -af'
        }
    }
}
