pipeline {
    agent any

    stages {
        stage('Hello') {
            steps {
                sh 'docker build -t buildirssi . -f ITE/GCL04/KK403281/Lab05/Docker-BLDR'
		sh 'docker run buildirssi'
            }
        }
        stage('Helloo') {
            steps {
                sh 'docker build -t testirssi . -f ITE/GCL04/KK403281/Lab05/Docker-Tescik'
		sh 'docker run testirssi'
            }
        }
    }
}
