pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh 'docker build -t IrssiBudowanie . -f ITE/GCL04/KK403281/Lab05/Docker-BLDR'
		sh 'docker run --name Kontenerek -dit --rm IrssiBudowanie'
		sh 'rm irssi || true'
		sh 'docker cp Kontenerek:irssi/build/src/fe-text/irssi .'
		sh 'docker kill Kontenerek'
            }
        }
        stage('Test') {
            steps {
                sh 'docker build -t IrssiTescik . -f ITE/GCL04/KK403281/Lab05/Docker-Tescik'
		sh 'docker run IrssiTescik'
            }
        }
	stage('deploy'){
	    steps {
		sh "docker kill deployKontener || true"
		sleep 2
		sh 'docker run --rm --name deployKontener -dit ubuntu'
		sh 'docker cp irssi deployKontener:.'
		sh 'docker container exec deployKontener sh -c "apt-get update"'
		sh 'docker container exec deployKontener sh -c "DEBIAN_FRONTEND="noninteractive" apt-get install -y libglib2.0"'
		sh "docker container exec deployKontener sh -c 'apt-get install -y libutf8proc-dev'"
		sh "docker container exec deployKontener sh -c './irssi --version'"
		sh "docker container kill deployKontener"
	    }
	}
	stage('publish'){
	    steps {
		archiveArtifacts artifacts: 'irssi'
	    }
	}
    }
}
