pipeline {
    agent {
        docker {
            image 'ubuntu'
            args '-u root:sudo -v $HOME/workspace/test:/test'
        }

    }

    stages {
		stage('Clone repo into vol') {
			steps {
				sh 'docker volume create vol-in'
				sh 'docker rm vol-out || true'
				sh 'docker run -v vol-in:/data --name vol-out busybox true'
				sh 'cd ~/ && ls vim || git clone https://github.com/vim/vim.git'
				sh 'docker cp ~/vim vol-out:/data'
				sh 'docker rm vol-out'
			}
        }
        stage('Build') {
            steps {
                sh "apt update"
                sh "apt install -y git libtool-bin make libncurses-dev"
                sh "git clone https://github.com/vim/vim.git || true"
                sh "cd vim && make"
            }
        }
        stage('Test') {
            steps {
                sh "cd vim && (make test || true)"
            }
        }
    }
}
