FROM mcr.microsoft.com/dotnet/sdk:3.1
RUN echo "Dockerfile running"

RUN git clone https://github.com/barisates/dotnet-core-xunit-example
WORKDIR dotnet-core-xunit-example/dotnet-core-xunit
RUN dotnet build