#!/usr/bin/python3
# -*- coding: UTF-8 -*-

import sys

messageFile = sys.argv[1]

file = open(messageFile, 'r')
message = file.readlines()
file.close()

title = "DB403024"
lab = "Lab02"

if not title in message[0]:
    print("Commit name is wrong")
    sys.exit(-1)
if not lab in "".join(message[1:]):
    print("Commit message is wrong")
    sys.exit(-1)

print("Commit name is correct")
