pipeline {
    agent any

    parameters {
        string(name: 'Name')
        string(name: 'Version')
    }

    stages{
        stage('Build') {
            steps {
                echo 'BUILD'
                dir('INO/GCL01/SG404037/lab05') {
                    sh 'docker build . -f Dockerfile1 -t builder'
                }
            }
        }
        stage('Tests') {
            steps {
                echo 'TESTS'
                dir('INO/GCL01/SG404037/lab05') {
                    sh 'docker build . -f Dockerfile2 -t tester'
                }
            }
        }
        
        stage('Deploy') {
            steps {
                echo 'DEPLOY'
                sh 'docker run --volume /var/jenkins_home/workspace/pipeline1/INO/GCL01/SG404037/lab05:/final builder mv -n build /final'
                dir('INO/GCL01/SG404037/lab05') {
                    sh 'docker build . -f Dockerfile3 -t deploy'
                }
                sh 'docker run --volume /var/jenkins_home/workspace/pipeline1/INO/GCL01/SG404037/lab05/build:/build -d -p 3000:80 deploy'
                sh 'docker stop $(docker ps -a -q)'
            }
        }
        
        stage('Publish') {
            steps {
                echo 'PUBLISH'
                dir('INO/GCL01/SG404037/lab05') {
                    sh 'docker build . -f Dockerfile4 -t publisher'
                }
                sh "docker run --volume /var/jenkins_home/workspace/pipeline1/INO/GCL01/SG404037/lab05:/final publisher mv pipeline.tar.xz /final"
            }
        }
    }
    
}

