pipeline {
			
	agent any
	
    parameters {
        string(name: 'Version', defaultValue: '1.0.0', description: 'Version')
        booleanParam(name: 'Promote', defaultValue: true, description: 'Promote statement')
        string(name: 'Dockerfiles', defaultValue: './ITE/GCL07/BS401926/lab05', description: 'Dockerfiles path')
    }
    
	stages {
		stage('Clone') {
			steps {
				echo 'Creating volume'
				sh 'docker volume create in_vol'
				sh 'docker rm tmp_container || true'
				sh 'docker run -v in_vol:/data --name tmp_container node'
				sh 'cd ~/ && ls nexe || git clone --recurse-submodules https://github.com/nexe/nexe.git'
				sh 'docker cp ~/nexe tmp_container:/data'
				sh 'docker rm tmp_container'
			}
		}
	    stage('Build') {
			steps {
				echo 'Building nexe with npm'
				dir('./ITE/GCL07/BS401926/lab05') {
				    sh 'pwd'
				    sh 'ls'
					sh 'docker build . -t nexe_build -f docker-build'
					sh 'docker volume create out_vol'
					sh 'docker run --mount type=volume,src="in_vol",dst=/nexe_app --mount type=volume,src="out_vol",dst=/nexe_app_build nexe_build bash -c "cd /nexe_app/nexe && npm i;ls"'
				}
			}
		}
		stage('Test') {
  			steps {
    				echo 'Nexe test'
      				dir("./ITE/GCL07/BS401926/lab05"){
      					sh 'docker build . -t nexe_test -f docker-test'
      					sh 'docker run -t --mount type=volume,src="out_vol",dst=/nexe_app_test nexe_test bash -c "ls; cd /nexe_app_test/nexe && npm test"'
      					}
    				}
			}
	
	}
}
