pipeline {
	agent any
    parameters {
        string(name: 'BRANCH', defaultValue: 'dev', description: '')
        booleanParam(name: 'RUN_TESTS', defaultValue: true, description: '')
        }
  	stages {
        stage("Clone"){
            steps {
              sh 'docker volume  create --name inputVol'
              sh 'docker volume  create --name outputVol'
              sh "docker build -t lz4clone . -f ITE/GCL04/MP401341/Lab05/DockerfileClone --build-arg BRANCH=${BRANCH}"
              sh 'docker run -v inputVol:/lz4 lz4clone'
                }
              }
        stage("Build") {
            steps {
                sh 'docker build -t build . -f ITE/GCL04/MP401341/Lab05/DockerfileBuild'
                sh 'docker run -v inputVol:/lz4 -v outputVol:/lz4pkg build'
            }
        }
        stage("Test") {
           when {
                  environment name: 'RUN_TESTS', value: "true"
            }
            steps {
                sh 'docker build -t test . -f ITE/GCL04/MP401341/Lab05/DockerfileTest --build-arg image=build'
                sh 'docker run -v inputVol:/lz4 test'
            }
        }
        stage("Deploy") {
            steps {
                sh 'echo WIP'
            }
        }
        stage("Publish") {
            steps {
                sh 'echo WIP'
            }
        }
  	}
     post {
      always {
        sh 'docker container prune -f'
        sh 'docker volume prune -f'
      }
      }
      
}

