pipeline {
	agent any
  	stages {
        stage("Clone"){
            steps {
              sh 'docker volume  create --name inputVol'
              sh 'docker volume  create --name outputVol'
              sh 'docker build -t lz4clone . -f ITE/GCL04/MP401341/Lab05/DockerfileClone'
              sh 'docker run -v inputVol:/lz4 lz4clone'
                }
              }
        stage("Build") {
            steps {
                sh 'docker build -t build . -f ITE/GCL04/MP401341/Lab05/DockerfileBuild'
                sh 'docker run -v inputVol:/lz4 -v outputVol:/lz4pkg build'
            }
        }
        stage("Test") {
            steps {
                sh 'docker build -t test . -f ITE/GCL04/MP401341/Lab05/DockerfileTest --build-arg image=build'
                sh 'docker run -v inputVol:/lz4 test'
            }
        }
        stage("Deploy") {
            steps {
                sh 'echo WIP'
            }
        }
        stage("Publish") {
            steps {
                sh 'echo WIP'
            }
        }
  	}
     post {
      always {
        sh 'docker container prune -f'
        sh 'docker volume prune -f'
      }
      }
      
}

