FROM maven:3.8.4-jdk-11
RUN git clone https://github.com/vtandonv/CalculatorUsingDevOps.git input_v

WORKDIR input_v
CMD mvn package
CMD cp -r target/* /public
CMD cp -r target /output_v/
CMD chmod 777 -R /public
