FROM ubuntu:20.04

ARG DEBIAN_FRONTEND=noninteractive
RUN echo 'Building dotnet build image'

RUN apt-get -y update
RUN apt-get -y upgrade
RUN apt-get -y install wget

RUN wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
RUN dpkg -i packages-microsoft-prod.deb
RUN rm packages-microsoft-prod.deb

RUN apt-get update; \
  apt-get install -y apt-transport-https && \
  apt-get update && \
  apt-get -y install dotnet-sdk-3.1
