#!/usr/bin/python

import sys, os, re

regex_id = r'\bMS401869(?=[ \-\_\n])'
regex_lab_no = r'\blab\d\d(?=[ \-\_\n])'

MSG_FILEPATH = sys.argv[1]
COMMIT_TYPE = sys.argv[2] if len(sys.argv) > 2 else None
SHA1 = sys.argv[3] if len(sys.argv) > 3 else None

print(f"MSG_FILEPATH: {MSG_FILEPATH}")
print(f"COMMIT_TYPE: {COMMIT_TYPE}")
print(f"SHA1: {SHA1}")

with open(MSG_FILEPATH, 'r') as f:
    msg_str = f.read()

if not re.search(regex_id, msg_str):
    print("The commit does not contain album number.")
    sys.exit(1)

if not re.search(regex_lab_no, msg_str):
    print("The commit does not contain lab number.")
    sys.exit(1)

sys.exit(0)

