FROM node:lts

WORKDIR /app

CMD apt update; apt upgrade -y
CMD bash /testagent/check.sh
CMD cd ./wire-desktop
CMD yarn
CMD yarn fix:other
CMD yarn test:types && yarn lint && yarn prestart && yarn build:ts:tests && yarn test:react && yarn test:bin && yarn clear:coverage