# syntax=docker/dockerfile:1 
FROM node:16.15.0

# CMD ['/usr/bin/npm', 'test', 'a', 'q']

CMD ["sh", "-c", "npm -f /volume_in/calculator run-script build && cp -r /volume_in/calculator/build ./volume_out && ls ./volume_out"]

