# syntax=docker/dockerfile:1
FROM node:16.15.0

WORKDIR volume_in
CMD ["sh", "-c", "rm -rf /volume_in/* && git clone https://github.com/ahfarmer/calculator.git"]
WORKDIR calculator
CMD ["sh", "ls"]
RUN npm install
