# syntax=docker/dockerfile:1
FROM node:16.15.0

WORKDIR volume_in
CMD ["sh", "-c", "rm -rf /volume_in/* && git clone https://github.com/ahfarmer/calculator.git"]
RUN ls
WORKDIR calculator
RUN ls
RUN npm install
