FROM node:lts

RUN apt-get -y update
RUN apt-get -y upgrade
RUN apt-get install -y rpm
RUN git clone https://github.com/aleksanderfilek/wire-desktop-devops.git
WORKDIR wire-desktop-devops
RUN yarn
RUN yarn build:linux
RUN pwd

