pipeline {
			
	agent any

	stages {
		stage('Clone git repo') {
			steps {
				echo 'Creating volme to input'
				sh 'docker volume create input-volume'
				sh 'docker rm tempContainer || true'
				sh 'docker run -v input-volume:/data --name tempContainer node'
				sh 'cd ~/ && ls express || git clone --recurse-submodules https://github.com/expressjs/express.git'
				sh 'docker cp ~/express tempContainer:/data'
				sh 'docker rm tempContainer'
			}
		}
	
	stage('Build') {
			steps {
				echo 'Buildig express with npm'
				dir("./ITE/GCL08/DZ404114") {
					sh 'docker build . -t express-build -f docker_build'
					sh 'docker volume create output-volume'
					sh 'docker run --mount type=volume,src="input-volume",dst=/myapp --mount type=volume,src="output-volume",dst=/myapp_build express-build bash -c "cd /myapp/express && npm i;cd ..;cp -R express /myapp_build"'
				}
			}
		}
	}
	stage('Test') {
			steps {
				echo 'Testing express with npm'
				dir("./ITE/GCL08/DZ404114") {
					sh 'docker build . -t express-test -f docker_test'
					sh 'docker run --mount type=volume,src="output-volume",dst=/myapp_test express-test bash -c "cd /myapp_test/express && npm test"'
				}
			}
		}
	}
}
