# Generated by Anaconda 36.16.2
# Generated by pykickstart v3.36
#version=F36
# Use graphical install
graphical

# Keyboard layouts
keyboard --vckeymap=pl --xlayouts='pl'
# System language
lang pl_PL.UTF-8

# Network information
network  --bootproto=dhcp --device=enp0s3 --ipv6=auto --activate
network  --hostname=lab9.agh

# plytka FULL jako URL/REPO uzywa "DVD", ale plytka NETINST od niedawna
# ...nie uzywa *nic*. Podajemy recznie zatem.
url --mirrorlist=http://mirrors.fedoraproject.org/mirrorlist?repo=fedora-29&arch=x86_64
repo --name=updates --mirrorlist=http://mirrors.fedoraproject.org/mirrorlist?repo=updates-released-f29&arch=x86_64

%packages
@^minimal-environment

%end

# Czyszczenie dyskow bezwarunkowo, bez pytania, w calosci
clearpart --all
autopart --type=lvm

# System timezone
timezone Europe/Warsaw --utc

# Root password
rootpw --iscrypted $y$j9T$6jaLJ3hXJtopO.3fHoVBAiq5$fUOI383Y/QRHrGyizbWSYIogQIbP/   
