pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
		git 'https://github.com/InzynieriaOprogramowaniaAGH/MDO2022_S.git'
		sh 'git checkout DK403865'
		sh 'git pull origin'
		sh 'docker build -t build:latest . -f ITE/GCL03/DK403865/Lab05/DockerfileBuild/Dockerfile'
            }
        }
	stage('Test') {
            steps {
                sh 'pwd'
            }
        }

    }
}
