pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
		git 'https://github.com/InzynieriaOprogramowaniaAGH/MDO2022_S.git'
		sh 'git checkout DK403865'
		sh 'git pull origin'
		sh 'cat ITE/GCL03/DK403865/Lab05/Dockerfiles/Dockerfile-build'
                sh 'docker build - < /ITE/GCL03/DK403865/Lab05/Dockerfiles/Dockerfile-build'
            }
        }
	stage('Test') {
            steps {
                sh 'pwd'
            }
        }

    }
}
