#!/usr/bin/python3
# -*- coding: UTF-8 -*-

import sys
import re

messageFile = sys.argv[1]

file = open(messageFile, 'r')
message = file.readlines()
file.close()

title_pattern = re.compile("[A-Z]{2}[0-9]{6}\n")
message_pattern = re.compile("(l|L)ab[0-9]{2}")

if not title_pattern.match(message[0]):
    print("❌❌ commit title does not contain required author initials and student id❗")
    sys.exit(-1)
if not message_pattern.match("\n".join(message[1:])):
    print("❌❌ commit message does not contain required lab no")
    sys.exit(-1)

print("✅✅ commit title and commit message are okay and may be committed")
