stages {
      stage('Setup_Build') {
          steps {
              
              sh 'docker volume create in'
              sh 'docker volume create out'
              sh 'docker volume ls'
             
              sh 'mkdir -p App'
              dir("App")
              {
                  git branch: "${params.Project_branch}",
                  url: ''
                  
                  sh 'docker container create --name copy -v in:/in busybox'
                  sh 'docker cp ./. copy:/in'
                  sh 'docker rm copy'
              
                  sh 'ls .'
                  sh 'ls GithubTestApp'
                  sh 'pwd'
              }
              
              sh 'mkdir -p Dockerfiles'
              dir("Dockerfiles")
              {
                  git branch: 'TG400423',
                  url: 'https://github.com/InzynieriaOprogramowaniaAGH/MDO2022_S.git'

                  sh "docker build -t build_app . -f ${params.Dockerfiles_path}/Dockerfile_Build"
                  sh "cd ${params.Dockerfiles_path} && ls -l"
                  sh 'ls .'
              }

          }
      }