pipeline {
	agent any
	stages {
      	stage('Build') {
         	 steps {
              
            	  git 'https://github.com/InzynieriaOprogramowaniaAGH/MDO2022_S.git'
                  sh 'git checkout KT401975'
				  git 'config --global user.email "kewin@tarnowski.biz"'
				  sh 'git config --global user.name "kawelos"'
				  sh 'git pull'
				  sh 'ls'
				  sh 'pwd'
				  sh 'cd ./ITE/GCL08/KT401975/Lab05/dockerfiles/build ; docker build -t builder:latest .'
              }
		}
     }
}